{
 "title": "Dashboard Administration Transcription AI",
 "tags": [
  "M2",
  "Whisper"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Taux de Succès vs Échecs",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status) (transcription_total)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Rapport de temps de traitement ",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(transcription_duration_seconds_sum) / sum(media_duration_seconds_total)"
    }
   ]
  },
  {
   "title": "Inférences par Type (SRT, TEXT, VIDEO)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (response_type) (transcription_total{status=\"success\"})",
     "legendFormat": "{{response_type}}"
    }
   ]
  }
 ]
}