{
 "title": "Dashboard Administration Transcription AI",
 "tags": [
  "M2",
  "Whisper"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Nb de demandes en succès",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(transcription_total{status=\"success\"})",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Nb de demandes en erreur",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(transcription_total{status=\"error\"})",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Demande en attente de transcription",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(transcription_queue_size)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Temps moyen de traitement ",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (transcription_duration_seconds_sum) / sum (transcription_total)"
    }
   ]
  },
  {
   "title": "Rapport de temps de traitement",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(transcription_duration_seconds_sum) / sum(media_duration_seconds_total)"
    }
   ]
  },
  {
   "title": "Inférences en succès par Type (SRT, TEXT, VIDEO)",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (response_type) (transcription_total{status=\"success\"})",
     "legendFormat": "{{response_type}}"
    }
   ]
  },
  {
   "title": "Inférences en erreur par Type (SRT, TEXT, VIDEO)",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 5, "x": 5, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (response_type) (transcription_total{status=\"error\"})",
     "legendFormat": "{{response_type}}"
    }
   ]
  },
  {
   "title": "Temps moyen de traitement par type",
   "type": "stat",
   "gridPos": { "h": 9, "w": 7, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (response_type)(transcription_duration_seconds_sum) / sum by (response_type)(transcription_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rapport de temps de traitement par type",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (response_type)(transcription_duration_seconds_sum) / sum by (response_type)(media_duration_seconds_total)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}